### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by turtlecreations** [ho-nl/magento2-Ho_Templatehints#29]
I get the folowing error  after installation via Composer.

Parse error: syntax error, unexpected '?' in /magento/vendor/honl/magento2-templatehints/Plugin/View/LayoutPlugin.php on line 150

I followed the steps in the readme

**Comment by Jeroenll** [comment]
This module will work with PHP 7 and up. I've updated these constraints on the develop branch. The line you mentions is a new PHP7 operator.
