### ISSUE TITLE
Other js events prevent output in console

### ISSUE THREAD

**Issue by UB3RL33T** [ho-nl/magento2-Ho_Templatehints#42]
I have a magento 2.2.6 installation. 
Shift clicking on a product image opens up the light box view of the product image, not logging any output to the console.

The same seems to be true for buttons having click events.

**Comment by amenk** [comment]
how can we solve that?

**Comment by paales** [comment]
You can use the console to do that https://github.com/ho-nl/magento2-Ho_Templatehints#hints-for-hidden-elements
