### ISSUE TITLE
PHP version support

### ISSUE THREAD

**Issue by onlinebizsoft** [ho-nl/magento2-Ho_Templatehints#43]
I think in README, we should state which version the module were tested with. But in composer we should allow any PHP version which likely working with instead of fixing specific versions because our module keep out of dated than PHP version update.

For now, please update composer to support any PHP 7.2.x

**Comment by onlinebizsoft** [comment]
For anyone who have problem installing this on newer PHP version, you can run composer with parameter  --ignore-platform-reqs for now

**Comment by Axel29** [comment]
Hi,

The dev-master version has the correct tag for PHP 7.2 on packagist, could you tag a version number to it so that we can install it via composer without requiring dev-master or using version `--ignore-platform-reqs` please?

Thank you.

**Comment by paales** [comment]
Will be fixed
