### ISSUE TITLE
Please can you make a new release for your PHP7.2 support commit?

### ISSUE THREAD

**Issue by max-atkins** [ho-nl/magento2-Ho_Templatehints#45]

**Comment by wclrz** [comment]
🆙

**Comment by bambamboole** [comment]
+1

**Comment by Axel29** [comment]
Hi,

The dev-master version has the correct tag for PHP 7.2 on packagist, could you tag a version number to it so that we can install it via composer without requiring dev-master or using version `--ignore-platform-reqs` please?

Thank you.

**Comment by max-atkins** [comment]
This will take literally a couple of minutes to solve but causes us endless "God dammit I forgot to --ignore-platform-reqs". I love using this module but I can't keep using it if this continues. :(

**Comment by emanuel-jacob** [comment]
+1

**Comment by FrankHarland** [comment]
I made a new release, should be available via packagist. Let me know if it works :)

**Comment by Axel29** [comment]
Great thanks!
