### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by bartdelvaux** [ho-nl/magento2-Ho_Templatehints#48]
Magento 2.3.3 supports PHP 7.3. Is it possible to add this version in the composer.json? 

https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-3-open-source.html

**Comment by emanueljacob** [comment]
+1

**Comment by emanuel-jacob** [comment]
+1

**Comment by judin** [comment]
+ 1

**Comment by sprankhub** [comment]
This has already been added in https://github.com/ho-nl/magento2-Ho_Templatehints/pull/49. So what we now need is a new release. Could you tag a new version, @FrankHarland / @JeroenVanLeusden / @paales? Thanks!

**Comment by paales** [comment]
@sprankhub Will do today or monday :) I've assigned @JeroenVanLeusden

**Comment by Jeroenll** [comment]
New release has been tagged!
