### ISSUE TITLE
Add PHP storm remote call support

### ISSUE THREAD

**Issue by amenk** [ho-nl/magento2-Ho_Templatehints#5]
Maybe with shift ctrl click or something like thst

**Comment by paales** [comment]
Good idea, was planning to include something like that. I was planning on adding the URL's to the hint it's self, but clicking right on an element and going to the template related to that element would be great as well.

**Comment by amenk** [comment]
also fine

**Comment by paales** [comment]
Ref: http://develar.org/idea-rest-api/#api-Platform-file

**Comment by amenk** [comment]
You can also steal it from AOE ATH :) also there is an xdebug file link
config Option which could be used to avoid the need to configure twice.

**Comment by paales** [comment]
@amenk Oh, reminds me, have to add some credits, where credits are due 😄 

I believe the above api is the new method, the remote call is deprecated.

**Comment by paales** [comment]
@amenk Implemented in 0.2.1
