### ISSUE TITLE
PHP requirements don't match Magento 2.4.4

### ISSUE THREAD

**Issue by Axel29** [ho-nl/magento2-Ho_Templatehints#58]
### Preconditions

1. Magento 2.4.4

### Steps to reproduce

1. Run `composer require-commerce --dev honl/magento2-templatehints`

### Expected result

1. No error is thrown
2. The module is installed

### Actual result

1. The following error is thrown because of PHP `~ 7.1` in the composer.json requirements while Magento 2.4.4 requires PHP >= 8.1:

```bash
Package honl/magento2-templatehints has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - honl/magento2-templatehints 0.2.5 requires php ~7.1 which does not match your installed version 8.1.1.
```

**Comment by BorisovskiP** [comment]
@JeroenVanLeusden @paales Are there any plans to update the requirements so that the module is compatible with Magento 2.4.4 ?

**Comment by paales** [comment]
I don't specifically have plans, but I will accept a PR :)

**Comment by tthierryEra** [comment]
I've created a quick fix PR that let me use this module in Magento 2.4.4 with php8.1

https://github.com/ho-nl/magento2-Ho_Templatehints/pull/59 
Not sure it's the best way to fix it, but it's the fastest

**Comment by paales** [comment]
Merged the PR and created a release https://github.com/ho-nl/magento2-Ho_Templatehints/releases/tag/0.3.0
